function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 25-Nov-2022 23:54:35

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'DisplayName','Van Daele, r_y = 0.014','Marker','o',...
    'Color',[0 0 1]);
set(plot1(2),'DisplayName','McLellan89, r_y = 0.081','Marker','+',...
    'LineStyle','--',...
    'Color',[0 1 0]);
set(plot1(3),'DisplayName','McLellan96, r_y = 0.082','Marker','*',...
    'LineStyle','-.',...
    'Color',[1 0 0]);
set(plot1(4),'DisplayName','Average, r_y = 0.059','LineWidth',5,...
    'Color',[0 1 1]);

% Create ylabel
ylabel('Population','FontSize',25,'Interpreter','latex');

% Create xlabel
xlabel('Time (yrs)','FontSize',25,'Interpreter','latex');

% Create title
title('The Population of Alaskan Brown Bears Over Time','FontSize',25,...
    'Interpreter','latex');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',20,'GridAlpha',1,'MinorGridAlpha',1,'XMinorGrid','on',...
    'YMinorGrid','on','ZMinorGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','FontSize',20);

